refactor temp folder creation

diff --git a/ci_deploy/generate-k8s-manifests b/ci_deploy/generate-k8s-manifests
--- a/ci_deploy/generate-k8s-manifests
+++ b/ci_deploy/generate-k8s-manifests
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
-# version: 2.0.0
+# version: 2.1.0
 
 set -eo pipefail
 
 function help() {
-    echo "Usage: APP_PATH='example-app' $0 [-h|--help] [-c|--clean] [-o|--output[=]<manifest-file-path>]"
+    echo "Usage: $0 [-h|--help] [-c|--clean] [-o|--output[=]<manifest-file-path>]"
 }
 
 function parse_arguments() {
@@ -52,11 +52,6 @@ function create_kustomization_file() {
     contents=$(yq e '.resources = []' -n)
     
     for file in ${path}/*; do
-        [ ! -f "${file}" ] && {
-            echo "⚠️  Files not found in: ${path} (maybe the FILE_CONTENT_*_BASE64 env variables are not set)" 1>&2
-
-            exit 2
-        }
         export file_path=$(basename "${file}")
         contents=$(echo "${contents}" | yq e '.resources += [strenv(file_path)]')
     done
@@ -66,16 +61,7 @@ function create_kustomization_file() {
 
 parse_arguments "$@"
 
-if [ "${APP_PATH}" == "" ]; then
-    echo "⚠️  'APP_PATH' not configured" 1>&2
-	help
-
-    exit 1
-fi
-
-tmp_app_dir="/tmp/${APP_PATH}"
-rm -rf "${tmp_app_dir}"
-mkdir -p "${tmp_app_dir}"
+tmp_app_dir="$(mktemp -d)"
 
 for file_content_base64_env in ${!FILE_CONTENT_*}; do
     if [[ "${file_content_base64_env}" =~ _PART[0-9]+_ ]]; then
@@ -92,8 +78,17 @@ for file_content_base64_env in ${!FILE_CONTENT_*}; do
     echo "${contents}" > "${tmp_app_dir}/${file_name}"
 done
 
+if [ ! "$(ls -A "${tmp_app_dir}" 2>/dev/null)" ]; then
+    echo "⚠️  Files not found. (maybe the FILE_CONTENT_*_BASE64 env variables are not set)" 1>&2
+    rm -rf "${tmp_app_dir}"
+
+    exit 1
+fi
+
 contents=$(kubectl kustomize "${tmp_app_dir}" 2>/dev/null \
     || (create_kustomization_file "${tmp_app_dir}" && kubectl kustomize "${tmp_app_dir}"))
+
+rm -rf "${tmp_app_dir}"
 
 if [ "${outputFile}" != "" ]; then
     outputFolder=$(dirname "${outputFile}")
